export const IMAGENET_CLASSES = {
  1: 'affenpinscher',
  2: 'afghan hound',
  3: 'african hunting dog',
  4: 'airedale',
  5: 'american staffordshire terrier',
  6: 'appenzeller',
  7: 'australian terrier',
  8: 'basenji',
  9: 'basset',
  10: 'beagle',
  11: 'bedlington terrier',
  12: 'bernese mountain dog',
  13: 'black-and-tan coonhound',
  14: 'blenheim spaniel',
  15: 'bloodhound',
  16: 'bluetick',
  17: 'border collie',
  18: 'border terrier',
  19: 'borzoi',
  20: 'boston bull',
  21: 'bouvier des flandres',
  22: 'boxer',
  23: 'brabancon griffon',
  24: 'briard',
  25: 'brittany spaniel',
  26: 'bull mastiff',
  27: 'cairn',
  28: 'cardigan',
  29: 'chesapeake bay retriever',
  30: 'chihuahua',
  31: 'chow',
  32: 'clumber',
  33: 'cocker spaniel',
  34: 'collie',
  35: 'curly-coated retriever',
  36: 'dandie dinmont',
  37: 'dhole',
  38: 'dingo',
  39: 'doberman',
  40: 'english foxhound',
  41: 'english setter',
  42: 'english springer',
  43: 'entlebucher',
  44: 'eskimo dog',
  45: 'flat-coated retriever',
  46: 'french bulldog',
  47: 'german shepherd',
  48: 'german short-haired pointer',
  49: 'giant schnauzer',
  50: 'golden retriever',
  51: 'gordon setter',
  52: 'great dane',
  53: 'great pyrenees',
  54: 'greater swiss mountain dog',
  55: 'groenendael',
  56: 'ibizan hound',
  57: 'irish setter',
  58: 'irish terrier',
  59: 'irish water spaniel',
  60: 'irish wolfhound',
  61: 'italian greyhound',
  62: 'japanese spaniel',
  63: 'keeshond',
  64: 'kelpie',
  65: 'kerry blue terrier',
  66: 'komondor',
  67: 'kuvasz',
  68: 'labrador retriever',
  69: 'lakeland terrier',
  70: 'leonberg',
  71: 'lhasa',
  72: 'malamute',
  73: 'malinois',
  74: 'maltese dog',
  75: 'mexican hairless',
  76: 'miniature pinscher',
  77: 'miniature poodle',
  78: 'miniature schnauzer',
  79: 'newfoundland',
  80: 'norfolk terrier',
  81: 'norwegian elkhound',
  82: 'norwich terrier',
  83: 'old english sheepdog',
  84: 'otterhound',
  85: 'papillon',
  86: 'pekinese',
  87: 'pembroke',
  88: 'pomeranian',
  89: 'pug',
  90: 'redbone',
  91: 'rhodesian ridgeback',
  92: 'rottweiler',
  93: 'saint bernard',
  94: 'saluki',
  95: 'samoyed',
  96: 'schipperke',
  97: 'scotch terrier',
  98: 'scottish deerhound',
  99: 'sealyham terrier',
  100: 'shetland sheepdog',
  101: 'shih-tzu',
  102: 'siberian husky',
  103: 'silky terrier',
  104: 'soft-coated wheaten terrier',
  105: 'staffordshire bullterrier',
  106: 'standard poodle',
  107: 'standard schnauzer',
  108: 'sussex spaniel',
  109: 'tibetan mastiff',
  110: 'tibetan terrier',
  111: 'toy poodle',
  112: 'toy terrier',
  113: 'vizsla',
  114: 'walker hound',
  115: 'weimaraner',
  116: 'welsh springer spaniel',
  117: 'west highland white terrier',
  118: 'whippet',
  119: 'wire-haired fox terrier',
  120: 'yorkshire terrier',
};